// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
<<<<<<< HEAD
  schema: "src/prisma/schema.prisma",
=======
  schema: "prisma/schema.prisma",
>>>>>>> origin/auth-feature
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
